In [1]:
import numpy as np
import vtk
import pymicro
import pymicro.crystal.microstructure
import os
import h5py
from esrf_mat_file import esrf_mat_file


In [17]:
nm = '/Volumes/PollockShare/Group Resources/Collaborative Projects/' \
     'Ti7_ESRF/id11/t5_/t5_dct_cen_1_/5_reconstruction/phase_01_vol.mat'

grainID = 1
grainIDs = [1,5,9,24]

matFile = esrf_mat_file(nm)
## Get correct reference frame
matFile.vol = matFile.vol.swapaxes(0,2)
matFile.vol = np.copy(matFile.vol,'C_CONTIGUOUS')
## Finished getting correct reference frame.
matFile.get_grain_orientations_dictionary() # read orientations from .mat files
matFile.get_microstructure_from_grains(grainIDs,name = '1_5_9_24')

file = /Volumes/PollockShare/Group Resources/Collaborative Projects/Ti7_ESRF/id11/t5_/t5_dct_cen_1_/5_reconstruction/phase_01_vol.mat
reading volume...
[u'rotation_angles', u'rotation_axes', u'vol']
shape =(424, 634, 634)
Getting rodrigues vector dictionary for (141,) grains
Working on grain 1
[ 0.02989752 -0.8187586   0.22855322]
Adding mesh for grain 1.
Working on grain 5
[ 0.78819892 -0.56153577  0.02370466]
Adding mesh for grain 5.
Working on grain 9
[-0.41470926  0.1857377  -0.0852515 ]
Adding mesh for grain 9.
Working on grain 24
[-0.40222288  0.55295877 -0.25101311]
Adding mesh for grain 24.


In [18]:
import pymicro.crystal.lattice

lambda_keV = 38.0
lambda_nm = 1.2398/ lambda_keV
Ti7Al = pymicro.crystal.lattice.Lattice.hexagonal(0.2931, 0.4694)  # nm

In [19]:
from pymicro.view.vtk_utils import *
import vtk

## Grain 1
grain1 = matFile.micro.get_grain(1)
hklplanes = [pymicro.crystal.lattice.HklPlane(0,0,1)]
grain1_with_planes = grain_3d(grain1, hklplanes, show_normal = False, plane_opacity = 1.0, show_orientation = True)
tr = vtk.vtkTransform()
tr.Translate(grain1.position)
grain1_with_planes.SetUserTransform(tr)

1
(0.9647058823529412, 0.9725490196078431, 0.4549019607843137)


In [20]:
## grain 5
grain5 = matFile.micro.get_grain(5)
hklplanes = [pymicro.crystal.lattice.HklPlane(0,0,1)]
grain5_with_planes = grain_3d(grain5, hklplanes, show_normal = False, plane_opacity = 1.0, show_orientation = True)
tr = vtk.vtkTransform()
tr.Translate(grain5.position)
grain5_with_planes.SetUserTransform(tr)

5
(0.6784313725490196, 0.2549019607843137, 0.34901960784313724)


In [21]:
## grain 9
grain9 = matFile.micro.get_grain(9)
hklplanes = [pymicro.crystal.lattice.HklPlane(0,0,1)]
grain9_with_planes = grain_3d(grain9, hklplanes, show_normal = False, plane_opacity = 1.0, show_orientation = True)
tr = vtk.vtkTransform()
tr.Translate(grain9.position)
grain9_with_planes.SetUserTransform(tr)

9
(0.8745098039215686, 0.00784313725490196, 0.7450980392156863)


In [22]:
## grain 24
grain24 = matFile.micro.get_grain(24)
hklplanes = [pymicro.crystal.lattice.HklPlane(0,0,1)]
grain24_with_planes = grain_3d(grain24, hklplanes, show_normal = False, plane_opacity = 1.0, show_orientation = True)
tr = vtk.vtkTransform()
tr.Translate(grain24.position)
grain24_with_planes.SetUserTransform(tr)

24
(0.9137254901960784, 0.36470588235294116, 0.22745098039215686)


In [30]:
from vtk.util.colors import white, grey, black
from pymicro.view.scene3d import Scene3D

s3d = Scene3D(display = False, ren_size = (800,800), name = 't5grains',background = black)

grain_bbox = box_3d(size = matFile.vol.shape, line_color=white)
axes = axes_actor(length = 100, fontSize = 60)
axes.GetXAxisCaptionActor2D().GetCaptionTextProperty().SetColor(grey)

size = np.shape(matFile.vol)
cam = setup_camera(size=np.shape(matFile.vol))
cam.Dolly(0.9)
cam.SetPosition(-2 * size[0], 2*size[1], 1 * size[2])
# cam.SetPosition(-2*size[0],0.5*size[1],0.5*size[2])
cam.SetViewUp(0,0,1)

s3d.add(grain_bbox)
s3d.add(grain1_with_planes)
s3d.add(grain5_with_planes)
s3d.add(grain9_with_planes)
s3d.add(grain24_with_planes)
s3d.add(axes)
s3d.set_camera(cam)
s3d.render()
cam.GetViewUp()

writing still image t5grains.png


(0.0, 0.0, 1.0)

In [14]:
del s3d

In [ ]:
del s3d
